---
title:       Codelet
tagline:     'A tech blog'
description: "A tech blog based on Mark Otto's Lanyon jekyll theme."
url:         https://skylerlee.github.io/codelet

author:
  name:      'Skyler Lee'
  url:       https://github.com/skylerlee

# Custom vars
version:     2.0.0

github:
  repo:      https://github.com/skylerlee/codelet

# Dependencies
markdown:    kramdown
highlighter: true

plugins:
  - jekyll-paginate

paginate: 5

# Permalinks
permalink:   pretty
