---
title:       Lanyon#
tagline:     'A Jekyll theme'
description: "A Jekyll theme that based on Mark Otto's Lanyon theme."
url:         https://skylerlee.github.io/codelet

author:
  name:      'Skyler Lee'
  url:       https://github.com/skylerlee

# Custom vars
version:     2.0.0

github:
  repo:      https://github.com/skylerlee/codelet

# Dependencies
markdown:    kramdown
highlighter: true

plugins:
  - jekyll-paginate

paginate: 5

# Permalinks
permalink:   pretty
