---
title:       Codelet
tagline:     'Keep code simple stupid'
description: 'My technical blog about thinking and coding'
url:         https://skylerlee.github.io/codelet

author:
  name:      'Skyler Lee'
  url:       https://github.com/skylerlee

github:
  repo:      https://github.com/skylerlee/codelet

# Dependencies
markdown:    kramdown
highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5

# Permalinks
permalink:   pretty
