---
title:       Codelet
tagline:     'A tech blog'
description: 'A tech blog using Enfield jekyll theme.'
url:         https://skylerlee.github.io/codelet

author:
  name:      'Skyler Lee'
  url:       https://github.com/skylerlee

github:
  repo:      https://github.com/skylerlee/codelet

# Dependencies
markdown:    kramdown
highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5

# Permalinks
permalink:   pretty
